//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempexAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class jsonAPI
    {
        public string CityID { get; set; }
        public string jsonString { get; set; }
        public string lastUpdated { get; set; }
    }
}
